services:
  zimbra:
    image: zimbra_docker
    container_name: zimbra-docker
    hostname: zimbra-docker.zimbra.io
    environment:
      - PASSWORD=Zimbra2017
    ports:
      - "25:25"
      - "80:80"
      - "443:443"
      - "465:465"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "8080:8080"
      - "8443:8443"
      - "7071:7071"
      - "9071:9071"
    dns:
      - 127.0.0.1
      - 8.8.8.8
