Vagrant.configure("2") do |config|
  # Configuração da box do Ubuntu 18.04
  config.vm.box = "generic/ubuntu1804"
  config.vm.box_version = "4.3.12"

  # Configura rede privada com IP estático
  config.vm.network "private_network", ip: "172.16.1.20"

  # Configuração de recursos da máquina virtual
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "12000"
    vb.cpus = 3
  end

  # Envia o arquivo de chave GPG para a máquina virtual
  config.vm.provision "file", source: "./zimbra-pubkey.asc", destination: "/tmp/zimbra-pubkey.asc"

  # Provisionar o script zimbrainstall.sh na máquina virtual
  config.vm.provision "file", source: "./zimbrainstall.sh", destination: "/home/vagrant/zimbrainstall.sh"

  # Configuração inicial
  config.vm.provision "shell", inline: <<-SHELL
    # Instala dependências necessárias
    sudo apt-get install -y dos2unix || { echo "[ERROR]: Failed to install dependencies. Exiting."; exit 1; }

    # Corrige final de linha e permissões no script de instalação
    dos2unix /home/vagrant/zimbrainstall.sh
    chmod +x /home/vagrant/zimbrainstall.sh
  SHELL

  # Mensagem após inicialização
  config.vm.provision "shell", inline: <<-SHELL, run: "always"
    echo "O script 'zimbrainstall.sh' foi executado automaticamente."
    echo "Se necessário, você pode verificar os logs ou executar novamente:"
    echo "sudo bash /home/vagrant/zimbrainstall.sh"
  SHELL
end
