Vagrant.configure("2") do |config|
  # Configuração da box do Ubuntu 18.04
  config.vm.box = "generic/ubuntu1804"
  config.vm.box_version = "4.3.12"

  # Configura rede privada com IP estático
  config.vm.network "private_network", ip: "172.16.1.20"

  # Configuração de recursos da máquina virtual
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "12000"
    vb.cpus = 3
  end

  # Provisionar o script zimbrainstall.sh na máquina virtual
  config.vm.provision "file", source: "./zimbrainstall.sh", destination: "/home/vagrant/zimbrainstall.sh"

  # Corrigir final de linha do arquivo para LF, permitir execução e executar o script automaticamente
  config.vm.provision "shell", inline: <<-SHELL
    # Instalar dos2unix caso não esteja disponível
    if ! command -v dos2unix &> /dev/null; then
      sudo apt-get update
      sudo apt-get install -y dos2unix
    fi

    # Corrigir final de linha e permissões
    dos2unix /home/vagrant/zimbrainstall.sh
    chmod +x /home/vagrant/zimbrainstall.sh

    # Executar o script
    sudo /home/vagrant/zimbrainstall.sh
  SHELL

  # Configurar mensagem após iniciar
  config.vm.provision "shell", inline: <<-SHELL, run: "always"
    echo "O script 'zimbrainstall.sh' foi executado automaticamente."
    echo "Se necessário, você pode verificar os logs ou executar novamente:"
    echo "sudo sh /home/vagrant/zimbrainstall.sh"
  SHELL
end
